# Generated by Django 3.2.8 on 2021-10-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarRate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'star_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('star_rate', models.IntegerField(blank=True, db_column='rate', null=True)),
            ],
        ),
    ]
