# Generated by Django 3.2.8 on 2021-11-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeight',
            fields=[
                ('user_weight_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_weight',
                'managed': False,
            },
        ),
    ]
