# Generated by Django 3.2.8 on 2021-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'infra_type',
                'managed': False,
            },
        ),
    ]
