# Generated by Django 3.2.8 on 2021-11-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0003_infratype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('star_rate', models.IntegerField(blank=True, db_column='rate', null=True)),
            ],
        ),
    ]
