# Generated by Django 3.2.9 on 2021-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_star'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfraType',
        ),
    ]
