# Generated by Django 3.2.9 on 2021-11-08 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0006_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserID',
        ),
    ]
