# Generated by Django 3.2.9 on 2021-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0002_infratype'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_rate', models.IntegerField(blank=True, null=True)),
                ('pharmacy_rate', models.IntegerField(blank=True, null=True)),
                ('playground_rate', models.IntegerField(blank=True, null=True)),
                ('park_rate', models.IntegerField(blank=True, null=True)),
                ('restaurant_rate', models.IntegerField(blank=True, null=True)),
                ('cafe_rate', models.IntegerField(blank=True, null=True)),
                ('salon_rate', models.IntegerField(blank=True, null=True)),
                ('deliver_rate', models.IntegerField(blank=True, null=True)),
                ('equip_rate', models.IntegerField(blank=True, null=True)),
                ('sell_rate', models.IntegerField(blank=True, null=True)),
                ('feed_rate', models.IntegerField(blank=True, null=True)),
                ('manage_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
