# Generated by Django 3.2.8 on 2021-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0003_auto_20211108_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hospital_rate', models.IntegerField(blank=True, null=True)),
                ('pharmacy_rate', models.IntegerField(blank=True, null=True)),
                ('playground_rate', models.IntegerField(blank=True, null=True)),
                ('park_rate', models.IntegerField(blank=True, null=True)),
                ('restaurant_rate', models.IntegerField(blank=True, null=True)),
                ('cafe_rate', models.IntegerField(blank=True, null=True)),
                ('salon_rate', models.IntegerField(blank=True, null=True)),
                ('deliver_rate', models.IntegerField(blank=True, null=True)),
                ('equip_rate', models.IntegerField(blank=True, null=True)),
                ('sell_rate', models.IntegerField(blank=True, null=True)),
                ('feed_rate', models.IntegerField(blank=True, null=True)),
                ('manage_rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User_table',
        ),
    ]
