# Generated by Django 3.2.8 on 2021-10-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('local_code', models.IntegerField(blank=True, db_column='LOCAL_CODE', null=True)),
                ('date_code', models.IntegerField(blank=True, db_column='DATE_CODE', null=True)),
                ('price', models.IntegerField(blank=True, db_column='PRICE', null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
    ]
